/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DynamicHeightVirtualList: typeof import('./src/components/DynamicHeightVirtualList.vue')['default']
    NormalList: typeof import('./src/components/NormalList.vue')['default']
    StaticHeightVirtualListObserver: typeof import('./src/components/StaticHeightVirtualListObserver.vue')['default']
    StaticHeightVirtualListScroll: typeof import('./src/components/StaticHeightVirtualListScroll.vue')['default']
  }
}
